id: A5177BE0E
title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the Everpresent
  Gurus'
type: translation
pechas:
- I4B4B30F4
- I464259DA
- I99A330BB
- IE740FD78
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:35:48.091980
  last_modified_at: 2023-01-04 11:35:48.091984
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I4B4B30F4/D007: 1B73
  I464259DA/14F9: 1B73
  I99A330BB/E5F8: 1B73
  IE740FD78/9D53: 1B73
